### ISSUE TITLE
rdflintのverup時、導入しているrepositoryにrdflintをverupさせるPullRequestを自動で上げる仕組みの検討

### ISSUE THREAD

**Issue by takemikami** [imas/rdflint#53]
rdflintの最新versionは以下で取得可能なので、circleciのcronjobとかで対応は可能と考えられる

```
$ curl -s https://jitpack.io/api/builds/com.github.imas/rdflint/latestOk | jq -r '.version'
0.0.9
```
see. https://jitpack.io/docs/API/#latest-build

導入しているリポジトリ側で対応して貰う想定で、
設定方法のドキュメント、スクリプト提供などを検討する。

**Comment by foooomio** [comment]
これはジャストアイデアなのですが、GitHub Actions の Action 化してしまうのはどうでしょうか。

使用する側のイメージとしてはこのような形になります。

```
on: pull_request
jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: imas/action-rdflint@v1
      with:
        version: latest # version or latest (default)
```
